# Change these first
owner: gourab28 # Your GitHub username
repo: server-monitor # Your Github repository name

# Add your sites here
sites:
  - name: CroSea.io
    url: https://crosea.io
  - name: RPC1
    url: https://mainnet.crosea.io/rpc1
  - name: RPC2
    url: https://mainnet.crosea.io/rpc2
  - name: RPC3
    url: https://mainnet.crosea.io/rpc3

status-website:
  baseUrl: /server-monitor # where "repo" is your repository name
  name: Your Status Website
