# Change these first
owner: gourab28 # Your GitHub username
repo: server-monitor # Your Github repository name

# Add your sites here
sites:
  - name: RiskYourBag.Com
    url: https://riskyourbag.com
  - name: Risk Server
    url: http://128.199.105.114:5000/


status-website:
  baseUrl: /server-monitor # where "repo" is your repository name
  name: Your Status Website
