owner: Gourab28 # GitHub username
repo: server-monitor # GitHub repository name
sites: # List of endpoints to track
  - name: RiskDice-Frontend
    url: https://riskyourbag.com
assignees: # Users to assign downtime issues (optional)
  - Gourab28
status-website:
  baseUrl: /server-monitor # where "repo" is your repository name
  name: RiskDice
